### ISSUE TITLE
Python script crashes out on python 3.10

### ISSUE THREAD

**Issue by alexhunsley** [coddingtonbear/taskwarrior-inthe.am#15]
```
❯ intheam setup
Traceback (most recent call last):
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/bin/intheam", line 5, in <module>
    from taskwarrior_inthe_am.cmdline import main
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/taskwarrior_inthe_am/cmdline.py", line 7, in <module>
    from .commands import COMMANDS, get_command_list
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/taskwarrior_inthe_am/commands.py", line 8, in <module>
    import keyring
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/keyring/__init__.py", line 12, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/keyring/core.py", line 13, in <module>
    from . import backend
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/keyring/backend.py", line 22, in <module>
    from .util import properties
  File "/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/Users/alexhunsley/.asdf/installs/python/3.10.1/lib/python3.10/collections/__init__.py)
```

I think changes in python 3.10 break it (they removed Iterables), see https://stackoverflow.com/a/72032097/348476

**Comment by navxio** [comment]
Same issue with python 3.9.8
