### ISSUE TITLE
https://inthe.am/api/v1/user/status/ endpoint returns 404

### ISSUE THREAD

**Issue by foobarbecue** [coddingtonbear/taskwarrior-inthe.am#3]
`aaron@kubuntu1604:~$ intheam setup                                                                               
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): inthe.am                        
Traceback (most recent call last):                                                                               
  File "/usr/local/bin/intheam", line 11, in <module>                                                            
    sys.exit(main())                                                                                             
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main                
    COMMANDS[args.command[0]]['function'](config, args, *extra)                                                  
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_inthe_am/commands.py", line 74, in setup              
    api = get_api_connection(config)                                                                             
  File "/usr/local/lib/python2.7/dist-packages/taskwarrior_inthe_am/api.py", line 53, in get_api_connection      
    status = s.get('https://inthe.am/api/v1/user/status/').json()                                                
  File "/home/aaron/.local/lib/python2.7/site-packages/requests/models.py", line 797, in json                    
    return json.loads(self.text, **kwargs)                                                                       
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads                                                 
    return _default_decoder.decode(s)                                                                            
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode                                                 
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                            
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode                                             
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
aaron@kubuntu1604:~$ python --version
Python 2.7.11+  `

**Comment by btashton** [comment]
looks like the service is only serving v2 api requests but a new version with this commit has not been cut yet
https://github.com/coddingtonbear/taskwarrior-inthe.am/commit/e193195ebc8a2718d03b2250bdcaaad63149755b
