### ISSUE TITLE
Crashed with JSONDecodeError

### ISSUE THREAD

**Issue by orsenthil** [coddingtonbear/taskwarrior-inthe.am#4]
```
$ intheam setup
Please enter your API key: (Input hidden)
Save to keyring? (N/Y): Y
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): inthe.am
Traceback (most recent call last):
  File "/Users/senthil/py/py36/bin/intheam", line 11, in <module>
    load_entry_point('taskwarrior-inthe.am==0.1.1', 'console_scripts', 'intheam')()
  File "/Users/senthil/py/py36/lib/python3.6/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/Users/senthil/py/py36/lib/python3.6/site-packages/taskwarrior_inthe_am/commands.py", line 74, in setup
    api = get_api_connection(config)
  File "/Users/senthil/py/py36/lib/python3.6/site-packages/taskwarrior_inthe_am/api.py", line 53, in get_api_connection
    status = s.get('https://inthe.am/api/v1/user/status/').json()
  File "/Users/senthil/py/py36/lib/python3.6/site-packages/requests/models.py", line 797, in json
    return json.loads(self.text, **kwargs)
  File "/Users/senthil/python3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/senthil/python3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/senthil/python3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.7', 65173), raddr=('74.207.247.134', 443)>
```

**Comment by vikrantvm** [comment]
I get the same error. Any workarounds for this?

**Comment by Traviskn** [comment]
I ran into the same JSON decode error, I was able to follow the [manual instructions](https://inthe.am/getting-started) and get it working, but it's too bad that this python script seems to be broken

**Comment by erm3nda** [comment]
Same here, JSON decode error while using the `intheam setup`...
