### ISSUE TITLE
setup command fails

### ISSUE THREAD

**Issue by cemsbr** [coddingtonbear/taskwarrior-inthe.am#6]
```
$ intheam setup
Traceback (most recent call last):
  File "/home/cemsbr/.pyenv/versions/3.6.2/bin/intheam", line 11, in <module>
    load_entry_point('taskwarrior-inthe.am==0.1.1', 'console_scripts', 'intheam')()
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/taskwarrior_inthe_am/commands.py", line 74, in setup
    api = get_api_connection(config)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/taskwarrior_inthe_am/api.py", line 19, in get_api_connection
    'api_key',                                         
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/keyring/core.py", line 41, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/cemsbr/.pyenv/versions/3.6.2/lib/python3.6/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```
There's nothing about it in README.rst and I can't get certificate and key from the web site.

**Comment by TheJF** [comment]
It seems to be missing this from the dependencies, but running `pip install keyrings.alt` seems to fix this.
