### ISSUE TITLE
intheam setup - write() argument must be str, not bytes

### ISSUE THREAD

**Issue by outofrange** [coddingtonbear/taskwarrior-inthe.am#7]
When executing `intheam setup`, after providing my API key, I get the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/bin/intheam", line 11, in <module>
    load_entry_point('taskwarrior-inthe.am==1.1.0', 'console_scripts', 'intheam')()
  File "/usr/lib/python3.7/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/usr/lib/python3.7/site-packages/taskwarrior_inthe_am/commands.py", line 120, in setup
    out.write(content)
TypeError: write() argument must be str, not bytes
```

When looking in `~/.tasks`, only `private.cert` was created.

Running with Python 3.7.0 on Arch Linux.

**Comment by jdeighton** [comment]
I solved this by changing the out object to be writable as binary.
in file commands.py at line 117:
```
-  with open(full_path, 'w') as out:
+  with open(full_path, 'wb') as out:
```

(basically added 'wb' instead of 'w')

Re-ran `intheam setup` and everything worked after that.  this was using python 3.7 on Fedora 29.
