### ISSUE TITLE
taskw.exceptions.TaskwarriorError: <exception str() failed> during intheam setup

### ISSUE THREAD

**Issue by rominf** [coddingtonbear/taskwarrior-inthe.am#8]
```
$ intheam setup
Please enter password for encrypted keyring: 
WARNING:taskwarrior_inthe_am.commands:Data directory /home/rominf/.tasks already exists.
INFO:taskwarrior_inthe_am.commands:File 'private.cert' written to /home/rominf/.tasks/private.cert.
INFO:taskwarrior_inthe_am.commands:File 'private.key' written to /home/rominf/.tasks/private.key.
INFO:taskwarrior_inthe_am.commands:File 'ca.cert.pem' written to /home/rominf/.tasks/ca.cert.pem.
INFO:taskwarrior_inthe_am.commands:Configuration written to /home/rominf/.taskrc.
INFO:taskwarrior_inthe_am.commands:Performing initial sync...
Traceback (most recent call last):
  File "/home/rominf/.local/bin/intheam", line 11, in <module>
    load_entry_point('taskwarrior-inthe.am==1.1.0', 'console_scripts', 'intheam')()
  File "/home/rominf/.local/lib/python3.6/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/home/rominf/.local/lib/python3.6/site-packages/taskwarrior_inthe_am/commands.py", line 170, in setup
    warrior.sync()
  File "/home/rominf/.local/lib/python3.6/site-packages/taskw/warrior.py", line 546, in sync
    self._execute('sync')
  File "/home/rominf/.local/lib/python3.6/site-packages/taskw/warrior.py", line 479, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <exception str() failed>
```

**Comment by orsenthil** [comment]
This bug is still present.

```
Traceback (most recent call last):
  File "/home/skumaran/.py/virtualenv/taskwarrior-intheam/bin/intheam", line 11, in <module>
    sys.exit(main())
  File "/home/skumaran/.py/virtualenv/taskwarrior-intheam/lib/python3.8/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/home/skumaran/.py/virtualenv/taskwarrior-intheam/lib/python3.8/site-packages/taskwarrior_inthe_am/commands.py", line 171, in setup
    warrior.sync()
  File "/home/skumaran/.py/virtualenv/taskwarrior-intheam/lib/python3.8/site-packages/taskw/warrior.py", line 546, in sync
    self._execute('sync')
  File "/home/skumaran/.py/virtualenv/taskwarrior-intheam/lib/python3.8/site-packages/taskw/warrior.py", line 479, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <exception str() failed>
```

**Comment by dkuku** [comment]
I got this error too - was with bugwarrior and jira but may be helpfull here:
https://github.com/ralphbean/bugwarrior/issues/746

**Comment by leandwo** [comment]
still hitting this
```
❯ intheam setup
Please enter your API key: (Input hidden) 
Save to keyring? (N/Y): Y
WARNING:taskwarrior_inthe_am.commands:Data directory /Users/leosol/.task already exists.
INFO:taskwarrior_inthe_am.commands:File 'private.cert' written to /Users/leosol/.task/private.cert.
INFO:taskwarrior_inthe_am.commands:File 'private.key' written to /Users/leosol/.task/private.key.
INFO:taskwarrior_inthe_am.commands:File 'ca.cert.pem' written to /Users/leosol/.task/ca.cert.pem.
INFO:taskwarrior_inthe_am.commands:Configuration written to /Users/leosol/.taskrc.
INFO:taskwarrior_inthe_am.commands:Performing initial sync...
Traceback (most recent call last):
  File "/usr/local/bin/intheam", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/taskwarrior_inthe_am/cmdline.py", line 57, in main
    COMMANDS[args.command[0]]['function'](config, args, *extra)
  File "/usr/local/lib/python3.9/site-packages/taskwarrior_inthe_am/commands.py", line 171, in setup
    warrior.sync()
  File "/usr/local/lib/python3.9/site-packages/taskw/warrior.py", line 546, in sync
    self._execute('sync')
  File "/usr/local/lib/python3.9/site-packages/taskw/warrior.py", line 479, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <exception str() failed>
```
